config/routes.rb
Rails.application.routes.draw do
  root 'recipes#index'
  resources :recipes, only: %i[index show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/recipes_controller.rb
# frozen_string_literal: true

class RecipesController < ApplicationController
  def index
    @recipes, @message = MarleySpoon::Recipe.all
  end

  def show
    @recipe = MarleySpoon::Recipe.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RecipesApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/recipes/index.html.erb
<div class="recipes-index">
  <header class='header'>
    <div class="index-header"></div>
    <h1>Recipes Test</h1>
    <%= image_tag 'cooking-bg.jpg'%>
  </header>
  <main>
    <% @recipes.each do |recipe| %>
      <div class="recipe-preview">
        <div class="recipe-image"><img src="<%= recipe.photo.url %>"/></div>
        <div class="title-link">
          <div class="title-backgroud"></div>
          <%= link_to recipe.title, recipe_path(recipe.id) %>
        </div>
      </div>
    <% end %>
  </main>
</div>

app/views/recipes/show.html.erb
<div class="recipes-show">
  <header>
    <div class="index-header"></div>
    <h1><%= @recipe.title %></h1>
    <img src="<%= @recipe.photo.url %>"/>
  </header>

  <main>
    <div class="details">
      <div class="calories">
        <span><%= @recipe.calories %> kcal</span>
      </div>
      <div class="description"><%= @recipe.description %></div>
      <div class="chef">
        <% if @recipe.chef&.name %>
          <span>Recipe by: <%= @recipe.chef.name %></span>
        <% end %>
      </div>
      <div class="tags">
        <% @recipe.tags.map do |tag| %>
          <div class="tag">
            <span>#<%= tag.name %></span>
          </div>
        <% end %>
      </div>
    </div>
  </main>
</div>